name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install tox, pytest, and dependencies
        run: |
            pip install tox
            pip install pytest
            pip install -r requirements.txt
      
      - name: Run tests
        run: tox
  
  publish-on-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: test
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
